; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Standard-Umgebung, die beim Klick auf "Build" genutzt wird
default_envs = esp32-s3-devkitc-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:generate_html_header.py

; Allgemeine Flash Einstellungen
; upload_port = /dev/ttyACM0      ; USB Verbindung
; upload_port = /dev/ttyUSB0     ; UART Verbindung
;upload_speed = 115200

; Monitor Einstellungen
monitor_port = /dev/ttyACM0
;monitor_port = /dev/ttyUSB0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize

; Flash Größe: Explizit auf 32MB setzen
; Dies verhindert Warnungen beim Upload und definiert die maximale Größe.
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432

; Partitionstabelle: Standardtabellen unterstützen keine 32MB.
; Verweis auf eine benutzerdefinierte CSV-Datei
board_build.partitions = default_16MB.csv

; Memory Type (Der kritische Parameter):
; Definiert das Hardware-Interface für Flash und PSRAM.
; Format: <flash_interface>_<psram_interface>
; Für N32R16V müssen beide auf Octal (OPI) stehen.
board_build.arduino.memory_type = opi_opi

; Flash Modus und Frequenz
; Setzt das Boot-Flag im Binary-Header auf OPI.
board_build.flash_mode = opi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

; PSRAM Konfiguration
; Spezifiziert den PSRAM-Typ für die Initialisierungsroutine.
board_build.psram_type = opi

lib_ldf_mode = deep+

lib_deps =
    ; --- Hardware Libraries ---
    adafruit/Adafruit ADS1X15 @ ^2.6.2
    adafruit/Adafruit BusIO@^1.17.4
    robtillaart/DAC8574@^0.1.2
    Wire
    kitesurfer1404/WS2812FX@^1.4.5
    
    ; --- Web & Network ---
    ESP32Async/ESPAsyncWebServer@3.6.0
    ESP32Async/AsyncTCP@3.3.2
    
    bblanchon/ArduinoJson@^7.4.2

; --- Build Flags ---
build_flags = 
    -D ESP32_ENV 
    -std=gnu++17
    -Iinclude
    ; Aktiviert die PSRAM-Unterstützung im Code-Preprozessor
    -DBOARD_HAS_PSRAM
    
    ; USB-CDC-Konfiguration für Serial Monitor
    ; 0: Ausgabe über UART0 (COM-Port am CP2102 Chip)
    ; 1: Ausgabe über nativen USB-Port (USB-OTG)
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_ignore = 
    Test

build_unflags = 
    -std=gnu++11

[env:native]
platform = native
test_framework = googletest
extra_scripts = pre:generate_html_header.py
build_flags = 
    -D NATIVE_ENV 
    -std=c++17 
    -lpthread
    -Iinclude

lib_ignore = 
    Adapters

lib_deps =
    bblanchon/ArduinoJson@^7.4.2